AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A lambda to perform custom redirection

Resources:
  Deno:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno
        SemanticVersion: 1.0.2

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist.zip
      MemorySize: 128
      Handler: main.handler
      Runtime: provided
      Layers:
        - !GetAtt Deno.Outputs.LayerArn
      Events:
        IndexResource:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          REDIRECT_URI: !Ref RedirectUri

Parameters:
  RedirectUri:
    Type: String
